version: '3.8'

services:
  igocloud:
    build: .
    container_name: igocloud_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.5G"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta